In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv("survey_results_public.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
Respondent                      64461 non-null int64
MainBranch                      64162 non-null object
Hobbyist                        64416 non-null object
Age                             45446 non-null float64
Age1stCode                      57900 non-null object
CompFreq                        40069 non-null object
CompTotal                       34826 non-null float64
ConvertedComp                   34756 non-null float64
Country                         64072 non-null object
CurrencyDesc                    45472 non-null object
CurrencySymbol                  45472 non-null object
DatabaseDesireNextYear          44070 non-null object
DatabaseWorkedWith              49537 non-null object
DevType                         49370 non-null object
EdLevel                         57431 non-null object
Employment                      63854 non-null object
Ethnicity                       45948 non-null object
Gender                          50557 non-null object
JobFactors                      49349 non-null object
JobSat                          45194 non-null object
JobSeek                         51727 non-null object
LanguageDesireNextYear          54113 non-null object
LanguageWorkedWith              57378 non-null object
MiscTechDesireNextYear          42379 non-null object
MiscTechWorkedWith              40314 non-null object
NEWCollabToolsDesireNextYear    47287 non-null object
NEWCollabToolsWorkedWith        52883 non-null object
NEWDevOps                       42686 non-null object
NEWDevOpsImpt                   41732 non-null object
NEWEdImpt                       48465 non-null object
NEWJobHunt                      42286 non-null object
NEWJobHuntResearch              41022 non-null object
NEWLearn                        56156 non-null object
NEWOffTopic                     50804 non-null object
NEWOnboardGood                  42623 non-null object
NEWOtherComms                   57205 non-null object
NEWOvertime                     43231 non-null object
NEWPurchaseResearch             37321 non-null object
NEWPurpleLink                   54803 non-null object
NEWSOSites                      58275 non-null object
NEWStuck                        54983 non-null object
OpSys                           56228 non-null object
OrgSize                         44334 non-null object
PlatformDesireNextYear          50605 non-null object
PlatformWorkedWith              53843 non-null object
PurchaseWhat                    39364 non-null object
Sexuality                       43992 non-null object
SOAccount                       56805 non-null object
SOComm                          56476 non-null object
SOPartFreq                      46792 non-null object
SOVisitFreq                     56970 non-null object
SurveyEase                      51802 non-null object
SurveyLength                    51701 non-null object
Trans                           49345 non-null object
UndergradMajor                  50995 non-null object
WebframeDesireNextYear          40024 non-null object
WebframeWorkedWith              42279 non-null object
WelcomeChange                   52683 non-null object
WorkWeekHrs                     41151 non-null float64
YearsCode                       57684 non-null object
YearsCodePro                    46349 non-null object
dtypes: float64(4), int64(1), object(56)
memory usage: 30.0+ MB

In [5]:
data.isnull().sum()

Respondent                          0
MainBranch                        299
Hobbyist                           45
Age                             19015
Age1stCode                       6561
CompFreq                        24392
CompTotal                       29635
ConvertedComp                   29705
Country                           389
CurrencyDesc                    18989
CurrencySymbol                  18989
DatabaseDesireNextYear          20391
DatabaseWorkedWith              14924
DevType                         15091
EdLevel                          7030
Employment                        607
Ethnicity                       18513
Gender                          13904
JobFactors                      15112
JobSat                          19267
JobSeek                         12734
LanguageDesireNextYear          10348
LanguageWorkedWith               7083
MiscTechDesireNextYear          22082
MiscTechWorkedWith              24147
NEWCollabToolsDesireNextYear    17174
NEWCollabToolsWorkedWith        11578
NEWDevOps                       21775
NEWDevOpsImpt                   22729
NEWEdImpt                       15996
                                ...
NEWJobHuntResearch              23439
NEWLearn                         8305
NEWOffTopic                     13657
NEWOnboardGood                  21838
NEWOtherComms                    7256
NEWOvertime                     21230
NEWPurchaseResearch             27140
NEWPurpleLink                    9658
NEWSOSites                       6186
NEWStuck                         9478
OpSys                            8233
OrgSize                         20127
PlatformDesireNextYear          13856
PlatformWorkedWith              10618
PurchaseWhat                    25097
Sexuality                       20469
SOAccount                        7656
SOComm                           7985
SOPartFreq                      17669
SOVisitFreq                      7491
SurveyEase                      12659
SurveyLength                    12760
Trans                           15116
UndergradMajor                  13466
WebframeDesireNextYear          24437
WebframeWorkedWith              22182
WelcomeChange                   11778
WorkWeekHrs                     23310
YearsCode                        6777
YearsCodePro                    18112
Length: 61, dtype: int64

In [7]:
data["Age"].fillna(data["Age"].mean(),inplace=True)

In [9]:
data[["Age"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 1 columns):
Age    64461 non-null float64
dtypes: float64(1)
memory usage: 503.7 KB

In [10]:
data.describe()

         Respondent           Age      CompTotal  ConvertedComp   WorkWeekHrs
count  64461.000000  64461.000000   3.482600e+04   3.475600e+04  41151.000000
mean   32554.079738     30.834111  3.190464e+242   1.037561e+05     40.782174
std    18967.442360      8.048367            inf   2.268853e+05     17.816383
min        1.000000      1.000000   0.000000e+00   0.000000e+00      1.000000
25%    16116.000000     26.000000   2.000000e+04   2.464800e+04     40.000000
50%    32231.000000     30.834111   6.300000e+04   5.404900e+04     40.000000
75%    49142.000000     32.000000   1.250000e+05   9.500000e+04     44.000000
max    65639.000000    279.000000  1.111111e+247   2.000000e+06    475.000000

# removing age less than 7 and greater than 90

In [11]:
data=data[(data["Age"]>=7)&(data["Age"]<=90)]

In [12]:
data.reset_index(drop=True)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,30.834111,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,30.834111,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,30.834111,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.000000,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.000000,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
5,6,I am a developer by profession,No,30.834111,14,NaN,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
6,7,I am a developer by profession,Yes,30.834111,18,Monthly,NaN,NaN,India,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
7,8,I am a developer by profession,Yes,36.000000,12,Yearly,116000.0,116000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
8,9,I am a developer by profession,No,30.000000,20,NaN,NaN,NaN,Tunisia,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js,jQuery,Just as welcome now as I felt last year,50.0,6,4
9,10,I am a developer by profession,Yes,22.000000,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
10,11,I am a developer by profession,Yes,23.000000,13,Yearly,31000.0,40070.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Django;React.js,Angular;Angular.js;Django;React.js,Just as welcome now as I felt last year,40.0,10,2
11,12,I am a developer by profession,No,49.000000,42,Monthly,1100.0,14268.0,Spain,European Euro,...,Easy,Appropriate in length,No,Mathematics or statistics,ASP.NET;jQuery,ASP.NET;jQuery,Just as welcome now as I felt last year,40.0,7,7
12,13,"I am not primarily a developer, but I write co...",Yes,53.000000,14,Monthly,3000.0,38916.0,Netherlands,European Euro,...,Neither easy nor difficult,Too long,No,NaN,NaN,NaN,A lot less welcome now than last year,36.0,35,20
13,14,I am a developer by profession,Yes,27.000000,13,Yearly,66000.0,66000.0,United States,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
14,15,I am a student who is learning to code,Yes,30.834111,13,NaN,NaN,NaN,France,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,4,NaN
15,16,I am a developer by profession,Yes,45.000000,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
16,17,I am a developer by profession,Yes,25.000000,14,Yearly,79000.0,79000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
17,18,I am a developer by profession,Yes,32.000000,12,Monthly,105000.0,1260000.0,United States,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
18,19,I am a developer by profession,No,24.000000,15,Yearly,83400.0,83400.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Express;React.js,Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
19,20,I am a developer by profession,Yes,40.000000,18,NaN,NaN,NaN,Spain,European Euro,...,Easy,Too short,No,"Another engineering discipline (such as civil,...",Spring,Angular.js;Spring,Just as welcome now as I felt last year,50.0,22,17
20,21,I am a student who is learning to code,Yes,23.000000,16,NaN,NaN,NaN,Belgium,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Gatsby;React.js;Spring;Vue.js,Angular;ASP.NET Core;Express;React.js;Spring,NaN,NaN,7,NaN
21,22,I am a developer by profession,Yes,30.834111,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
22,23,I am a developer by profession,Yes,27.000000,14,NaN,NaN,NaN,Germany,European Euro,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Somewhat less welcome now than last year,40.0,8,3
23,24,I am a developer by profession,Yes,45.000000,14,Yearly,85000.0,91883.0,Germany,European Euro,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,42.0,30,20
24,25,I am a developer by profession,No,30.834111,25,Monthly,NaN,NaN,Portugal,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,23,18
25,26,I am a developer by profession,No,30.834111,12,Yearly,94000.0,71093.0,Canada,Canadian dollar,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",NaN,Django;React.js,Just as welcome now as I felt last year,40.0,17,10
26,27,"I used to be a developer by profession, but no...",Yes,30.834111,12,NaN,NaN,NaN,United States,NaN,...,Easy,Appropriate in length,No,"A humanities discipline (such as literature, h...",Flask,Flask,Just as welcome now as I felt last year,NaN,20,20
27,28,I am a student who is learning to code,Yes,30.834111,22,NaN,NaN,NaN,China,NaN,...,Neither easy nor difficult,Too long,No,"A health science (such as nursing, pharmacy, r...",NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
28,29,I am a student who is learning to code,Yes,18.000000,15,NaN,NaN,NaN,Ukraine,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery...,NaN,Not applicable - I did not use Stack Overflow ...,NaN,Less than 1 year,NaN
29,30,I am a developer by profession,Yes,30.834111,14,Yearly,30000.0,38778.0,United Kingdom,Pound sterling,...,Neither easy nor difficult,Too long,No,"Information systems, information technology, o...",Express;React.js;Vue.js,Express;Vue.js,A lot less welcome now than last year,37.0,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64406,61121,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64407,61490,NaN,Yes,30.834111,14,NaN,NaN,NaN,United Kingdom,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Ruby on Rails,Flask;jQuery;Vue.js,Just as welcome now as I felt last year,NaN,13,NaN
64408,61561,NaN,Yes,64.000000,18,NaN,NaN,NaN,France,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Information systems, information technology, o...",Angular.js;jQuery;React.js;Vue.js,jQuery,A lot more welcome now than last year,NaN,30,NaN
64409,61570,NaN,No,30.834111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64410,61907,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Malaysia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64411,61918,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64412,61983,NaN,Yes,30.834111,25,NaN,NaN,NaN,Pakistan,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Django;Flask,NaN,NaN,NaN,Less than 1 year,3
64413,62391,NaN,Yes,30.834111,Younger than 5 years,NaN,NaN,NaN,Morocco,NaN,...,Neither easy nor difficult,Too short,NaN,NaN,Angular.js;Express;React.js;Ruby on Rails,Angular.js;Express;React.js;Ruby on Rails,NaN,NaN,Less than 1 year,Less than 1 year
64414,62464,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
64415,62605,NaN,No,30.834111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64416,62834,NaN,Yes,17.000000,10,NaN,NaN,NaN,Canada,NaN,...,Easy,Appropriate in length,No,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,7,NaN
64417,62954,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64418,63077,NaN,Yes,30.834111,20,NaN,NaN,NaN,United States,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,4,NaN
64419,63396,NaN,Yes,30.834111,24,NaN,NaN,NaN,Monaco,NaN,...,NaN,NaN,NaN,NaN,Gatsby,Gatsby,NaN,NaN,1,NaN
64420,63452,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Russian Federation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64421,63640,NaN,Yes,30.834111,8,NaN,NaN,NaN,Australia,NaN,...,NaN,NaN,No,NaN,Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Somewhat more welcome now than last year,NaN,6,2
64422,63796,NaN,Yes,30.834111,16,NaN,NaN,NaN,Bangladesh,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,6,3
64423,63820,NaN,Yes,30.834111,17,NaN,NaN,NaN,Nepal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot less welcome now than last year,NaN,3,NaN
64424,63994,NaN,Yes,30.834111,27,NaN,NaN,NaN,Saudi Arabia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot more welcome now than last year,NaN,Less than 1 year,Less than 1 year
64425,64013,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Bulgaria,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,NaN,NaN,NaN
64426,64104,NaN,Yes,30.834111,19,NaN,NaN,NaN,Poland,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,2,NaN
64427,64236,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64428,64330,NaN,Yes,30.834111,5,NaN,NaN,NaN,Thailand,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
64429,64480,NaN,Yes,30.834111,21,NaN,NaN,NaN,Morocco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,3,NaN
64430,64567,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Netherlands,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET Core,NaN,NaN,NaN,NaN
64431,64858,NaN,Yes,30.834111,16,NaN,NaN,NaN,United States,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64432,64867,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Morocco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64433,64898,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Viet Nam,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64434,64925,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Poland,NaN,...,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
64435,65112,NaN,Yes,30.834111,NaN,NaN,NaN,NaN,Spain,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [14]:
data.describe()

         Respondent           Age      CompTotal  ConvertedComp   WorkWeekHrs
count  64436.000000  64436.000000   3.481400e+04   3.474400e+04  41139.000000
mean   32555.489230     30.817255  3.191564e+242   1.036389e+05     40.779728
std    18966.194247      7.913740            inf   2.265406e+05     17.808019
min        1.000000      7.000000   0.000000e+00   0.000000e+00      1.000000
25%    16120.750000     26.000000   2.000000e+04   2.464800e+04     40.000000
50%    32233.500000     30.834111   6.300000e+04   5.404900e+04     40.000000
75%    49140.250000     32.000000   1.250000e+05   9.500000e+04     44.000000
max    65639.000000     89.000000  1.111111e+247   2.000000e+06    475.000000

In [25]:
data.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
       'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode',
       'YearsCodePro'],
      dtype='object')

# india coders

In [29]:
india=data[data["Country"]=="India"]

In [44]:
india.dropna(inplace=True)

C:\Users\Ganesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [46]:
prolang={}
for i in india["LanguageWorkedWith"]:
    for j in i.split(';'):
        if j in prolang:
            prolang[j]+=1
        else:
            prolang[j]=1

In [47]:
prolang

{'HTML/CSS': 188,
 'JavaScript': 212,
 'TypeScript': 92,
 'C': 56,
 'C++': 52,
 'Java': 120,
 'SQL': 151,
 'Ruby': 17,
 'C#': 70,
 'Python': 111,
 'Bash/Shell/PowerShell': 59,
 'Objective-C': 8,
 'PHP': 63,
 'Go': 16,
 'R': 17,
 'Kotlin': 20,
 'Swift': 9,
 'Scala': 9,
 'Dart': 14,
 'Rust': 7,
 'Perl': 5,
 'VBA': 7,
 'Assembly': 3,
 'Haskell': 2,
 'Julia': 1}

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
"(HTML/CSS, JavaScript, TypeScript, C, C++, Java, SQL, Ruby, C#, Python, Bash/Shell/PowerShell, Objective-C, PHP, Go, R, Kotlin, Swift, Scala, Dart, Rust, Perl, VBA, Assembly, Haskell, Julia)",188,212,92,56,52,120,151,17,70,111,...,20,9,9,14,7,5,7,3,2,1